FROM apache/airflow:2.6.0-python3.8

FROM apache/airflow:2.6.0-python3.9
# Install python packages
RUN pip install mlflow==2.3.0
RUN pip install pycaret==3.0.0
RUN pip install scikit-learn==1.2.2
RUN pip install scipy==1.11.4
RUN pip install boto3==1.26.121
RUN pip install requests==2.28.2
RUN pip install joblib==1.3.0
RUN pip install shap==0.45.1