name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Mlflow Docker image
        run: docker build ./mlflow -t ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:1.0.0

      - name: Push Mlflow Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:1.0.0

      - name: Build Inference Docker image
        run: docker build ./inference -t ${{ secrets.DOCKERHUB_USERNAME }}/inference:1.0.0

      - name: Push Inference Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/inference:1.0.0

      - name: Build Streamlit Docker image
        run: docker build ./streamlit -t ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:1.0.0

      - name: Push Streamlit Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:1.0.0
